application: appengineapp     # .appspot.com
version: 1
runtime: python27
api_version: 1
threadsafe: true

#env_variables:
#  theme: 'default'

#default_expiration: "30d"

skip_files:
    - ^(.*/)?app\.yaml
    - ^(.*/)?app\.yml
    - ^(.*/)?#.*#
    - ^(.*/)?.*~
    - ^(.*/)?.*\.py[co]
    - ^(.*/)?.*/RCS/.*
    - ^(.*/)?\..*
    - ^(.*/)?tests$
    - ^(.*/)?test$
    - ^test/(.*/)?
    - ^COPYING.LESSER
    - ^README\..*
    - \.gitignore
    - ^\.git/.*
    - \.*\.lint$
    - ^fabfile\.py
    - ^testrunner\.py
    - ^grunt\.js
    - ^node_modules/(.*/)?

builtins:
    - appstats: off   #/_ah/stats/
    - deferred: on    
    - remote_api: on  #/_ah/remote_api/
    - django_wsgi: on

handlers:
    - url: /images(.*\.(gif|png|jpg))
      static_files: static/images\1
      upload: static/images(.*\.(gif|png|jpg))

    - url: /css
      mime_type: text/css
      static_dir: static/css

    - url: /js
      mime_type: text/javascript
      static_dir: static/js
      
#    - url: /admin.*
#      script: admin.app
#      login: admin
  
    - url: /.*
      script: main.app            
    # secure: always          
           
libraries:
    - name:    django
      version: latest
    - name:    webapp2
      version: latest  # "2.6" or other actual version here
    - name:    pycrypto
      version: latest # "2.6" or other.      

#error_handlers:
  # Only errors with error_code, don't put a default error here
#  - error_code: over_quota
#    file: app/templates/errors/over_quota.html
#
#  - error_code: dos_api_denial
#    file: app/templates/errors/dos_api_denial.html
#
#  - error_code: timeout
#    file: app/templates/errors/timeout.html
     
